---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nx-cisco-networking-metal-ironcore-dev-v1alpha1-nveconfig
  failurePolicy: Fail
  name: nveconfig-cisco-nx-v1alpha1.kb.io
  rules:
  - apiGroups:
    - nx.cisco.networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nveconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-interface
  failurePolicy: Fail
  name: interface-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - interfaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-nve
  failurePolicy: Fail
  name: nve-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nves
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-metal-ironcore-dev-v1alpha1-vrf
  failurePolicy: Fail
  name: vrf-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.metal.ironcore.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vrfs
  sideEffects: None
