apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  name: spine1-lo0
spec:
  deviceRef:
    name: spine1
  name: lo0
  description: Router-ID Spine1
  adminState: Up
  type: Loopback
  ipv4:
    addresses:
      - 10.0.0.1/32
