apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: BGP
metadata:
  name: spine1-bgp
spec:
  deviceRef:
    name: spine1
  asNumber: 65000
  routerId: 10.0.0.1
  addressFamilies:
    ipv4Unicast:
      enabled: true
