apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Device
metadata:
  labels:
    networking.metal.ironcore.dev/role: evpn-spine
  name: spine1
spec:
  endpoint:
    address: 192.168.5.2:50001
    secretRef:
      name: fabric-credentials
