apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: ManagementAccess
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
    networking.metal.ironcore.dev/device-name: leaf1
  name: managementaccess
spec:
  deviceRef:
    name: leaf1
  # See: ./cisco/nx/v1alpha1_managementaccessconfig.yaml
  # providerConfigRef:
  #   apiVersion: nx.cisco.networking.metal.ironcore.dev/v1alpha1
  #   kind: ManagementAccessConfig
  #   name: nx-mgmt
  grpc:
    port: 9339
    certificateId: mytrustpoint
    vrfName: default
    gnmi:
      maxConcurrentCall: 16
      keepAliveTimeout: 600s
  ssh:
    timeout: 120s
    sessionLimit: 10
