apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: VTEP
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
    networking.metal.ironcore.dev/device-name: leaf1
  name: vtep1
spec:
  deviceRef:
    name: leaf1
  enabled: true
  hostReachability: BGP
  suppressArp: true
  primaryInterfaceRef:
    name: lo0
  anycastInterfaceRef:
    name: lo1
  providerConfigRef:
    apiVersion: nx.cisco.networking.metal.ironcore.dev/v1alpha1
    kind: NVE
    name: nve1
