apiVersion: network.ironcore.dev/v1alpha1
kind: IGP
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
    network.ironcore.dev/device-name: leaf1
  name: underlay-isis-area-0
spec:
  name: underlay-isis-area-0
  isis:
    net: 49.0001.0001.0000.0001.00
    level: Level1
    overloadBit:
      onStartup: 600
    addressFamilies:
      - v4-unicast
