apiVersion: networking.cloud.sap/v1alpha1
kind: Banner
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
    networking.cloud.sap/device-name: leaf1
  name: banner
spec:
  deviceRef:
    name: leaf1
  message:
    inline: |
      ###################################################
      #   WARNING: Unauthorized access is prohibited.   #
      #   All connections are logged and monitored.     #
      ###################################################
