apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: PIM
metadata:
  name: leaf3-pim
spec:
  deviceRef:
    name: leaf3
  rendezvousPoints:
    - address: 10.0.0.100
      multicastGroups:
        - 224.0.0.0/4
  interfaceRefs:
    - name: leaf3-lo0
      mode: Sparse
    - name: leaf3-lo1
      mode: Sparse
    - name: leaf3-eth1-1
      mode: Sparse
    - name: leaf3-eth1-2
      mode: Sparse
