apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: PIM
metadata:
  name: spine1-pim
spec:
  deviceRef:
    name: spine1
  rendezvousPoints:
    - address: 10.0.0.100
      multicastGroups:
        - 224.0.0.0/4
      anycastAddresses:
        - 10.0.0.1
        - 10.0.0.2
  interfaceRefs:
    - name: spine1-lo0
      mode: Sparse
    - name: spine1-lo1
      mode: Sparse
    - name: spine1-eth1-1
      mode: Sparse
    - name: spine1-eth1-2
      mode: Sparse
    - name: spine1-eth1-3
      mode: Sparse
