apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  annotations:
    nx.cisco.networking.metal.ironcore.dev/spanning-tree-port-type: "network"
    nx.cisco.networking.metal.ironcore.dev/vpc-domain: |
      {
        "src": "10.1.1.1",
        "dst": "10.1.1.2",
        "vrf": "VPC_KEEPALIVE"
      }
  name: leaf1-po1
spec:
  deviceRef:
    name: leaf1
  name: po1
  description: vPC Peer-Link
  adminState: Up
  type: Aggregate
  switchport:
    mode: Trunk
    nativeVlan: 1
  aggregation:
    controlProtocol:
      mode: Active
    memberInterfaceRefs:
      - name: leaf1-eth1-31
      - name: leaf1-eth1-32
