apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: EVPNInstance
metadata:
  name: leaf1-vxlan-100010
spec:
  deviceRef:
    name: leaf1
  vni: 100010
  type: Bridged
  multicastGroupAddress: 239.1.1.100
  vlanRef:
    name: leaf1-vlan-10
