apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  name: leaf2-eth1-30
spec:
  deviceRef:
    name: leaf2
  name: eth1/30
  description: vPC Keepalive
  adminState: Up
  type: Physical
  vrfRef:
    name: leaf2-vpc-keepalive
  ipv4:
    addresses:
      - 10.1.1.2/30
