apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  name: spine1-eth1-3
spec:
  deviceRef:
    name: spine1
  name: eth1/3
  description: Spine1 to Leaf3
  adminState: Up
  type: Physical
  mtu: 9216
  ipv4:
    unnumbered:
      interfaceRef:
        name: spine1-lo0
