apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  name: spine2-eth1-2
spec:
  deviceRef:
    name: spine2
  name: eth1/2
  description: Spine2 to Leaf2
  adminState: Up
  type: Physical
  mtu: 9216
  ipv4:
    unnumbered:
      interfaceRef:
        name: spine2-lo0
