apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Interface
metadata:
  name: leaf3-lo1
spec:
  deviceRef:
    name: leaf3
  name: lo1
  description: VTEP Leaf3
  adminState: Up
  type: Loopback
  ipv4:
    addresses:
      - 10.0.1.12/32
